### ISSUE TITLE
Exception in example

### ISSUE THREAD

**Issue by benprofessionaledition** [jdeng/gomxnet#2]
Hello, I've followed the documentation to get everything installed and I'm running into this issue when attempting to run the example:

> ## panic: Cannot find argument 'fix_gamma', Possible Arguments:
> 
> eps : float, optional, default=1e-10
>     Epsilon to prevent div 0
> momentum : float, optional, default=0.1
>     Momentum for moving average
> 
> goroutine 1 [running]:
> panic(0x4231420, 0xc422f420b0)
>   /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
> main.main()
>   /usr/local/go/bin/src/github.com/jdeng/gomxnet/example/main.go:56 +0xad4

This issue seems to be caused by the statement "goxmnet.NewPredictor(...)", which _appears_ to call MXPredCreate in the native code (predict.go line 54 and then mxnet.cc line 20000 something). I'm sadly unfamiliar with debugging tools for C++ and Go, so I can't get a whole lot further than that. My suspicion is that I've failed in the setup somehow. I'm using OpenBLAS 2.18.2, and the Inception-BN model.

**Comment by vadmeste** [comment]
> panic: Cannot find argument 'fix_gamma', Possible Arguments:
> 
> eps : float, optional, default=1e-10
> Epsilon to prevent div 0
> momentum : float, optional, default=0.1
> Momentum for moving average

I have the same error message. It would be great if someone fix it.

**Comment by vadmeste** [comment]
@lqstuart, I think I understood the problem.. mxnet code in this repository is quite outdated, it seems you need to apply "mxnet amalgamation (this is optional. A pre-generated mxnet.cc is already in the directory.)" section in README.md

I didn't test it but I downloaded an earlier version of the mxnet model (https://www.dropbox.com/s/es1xn9404p8isia/Inception21k-Full.zip?dl=1) and it worked just fine.

**Comment by songtianyi** [comment]
Is there anyone build pass?
Too much trouble for building.
